name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: mingw-w64-x86_64-gcc

    - name: Build CherryNote
      shell: msys2 {0}
      run: |
        gcc CherryNote.c -o CherryNote.exe -lgdi32 -lcomctl32 -luser32 -lmsimg32 -mwindows -municode

    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CherryNote-Binary
        path: CherryNote.exe
